---
title: "Fitness figures code updated Mar2024"
author: "Toshiko Tanaka"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

# build the data frame

updated to scale G22DURTN



```{r}
library(tidyverse)
library(confintr)
libdata <- "C:/Users/tanakato/OneDrive - National Institutes of Health/TOSH PROJECTS/Somascan/BLSA proteomics/BLSA_7K/Data/QC'd BLSA SomaLogic Data (4.24.22)/"
projdat <- "C:/Users/tanakato/OneDrive - National Institutes of Health/TOSH PROJECTS/Somascan/BLSA proteomics/BLSA_7K/Analysis/VO2max/"

all.scores <- read.table(paste0(projdat,"0_codes_instructions/from Andrew/Calculated_score_BLSA_scaled.csv"),header=T,sep=",")
```

# correlation between score and fitness

```{r}
ggplot(data=all.scores, aes(x=G22DURTN_score, y=vo2_max)) +
  geom_point() +
  theme_bw() +
  ggpubr::stat_cor(cor.coef.name = "rho", method="spearman") +
 labs(title = "BLSA LASSO model performance",
       x = "Proteomic CRF Score",
       y = expression(VO[2]*max))
ggsave("scaled_BLSA_score_ett_corr.pdf", width = 4, height = 3)
```

if the code above is "overplotted" then rasterizing will help with visualization
```{r}
dataForPlots <- all.scores %>% mutate(d = densCols(all.scores$vo2_max, all.scores$G22DURTN_score, colramp = colorRampPalette(rev(rainbow(10, end = 4/6)))))

ggplot(data=dataForPlots, aes(x=G22DURTN_score, y=vo2_max)) +
  geom_point(aes(col=d)) +
  scale_color_identity() +
  theme_bw() +
  ggpubr::stat_cor(cor.coef.name = "rho", method="spearman") +
  labs(title = "BLSA LASSO model performance",
       x = "Proteomic CRF Score",
       y = expression(VO[2]*max))
ggsave("scaled_BLSA_score_ett_corr.pdf", width = 4, height = 3)

# we want this output so we can meta-analyze the correlation between the protein score and fitness across cohorts
confintr::ci_cor(dataForPlots$G22DURTN_score,
                 dataForPlots$vo2_max,
                 method = "spearman", type = "bootstrap", R = 5000)
```

# age

```{r}

temp <- all.scores %>% mutate(d = densCols(all.scores$Age, all.scores$G22DURTN_score, colramp = colorRampPalette(rev(rainbow(10, end = 4/6)))))

ggplot(data=temp, aes(x=Age, y=G22DURTN_score)) +
  geom_point(size=0.5, aes(col = d)) +
  scale_color_identity() +
  theme_bw() +
  ggpubr::stat_cor(cor.coef.name = "rho", method="spearman", label.y.npc = "bottom") +
  labs(title = "BLSA LASSO model performance",
       subtitle = "All BLSA participants",
       y = "Proteomic CRF Score",
       x = "Age")
ggsave("scaled_BLSA_score_age_corr.pdf", width = 4, height = 3)
```


# sex and race

you can change this to be white / non-white if more appropriate
```{r}
# print out this linear model for the comparison testing, will add later in power point
all.scores$RACE <- ifelse(all.scores$race=="White","White","Non-White")
all.scores$SEX  <- ifelse(all.scores$sex==1,"Male","Female")
table(all.scores$sex)

summary(lm(G22DURTN_score ~ SEX*RACE, data=all.scores))

colorset <- c("Female" = "darkorange", "Male" = "forestgreen")

ggplot(all.scores, aes(x=G22DURTN_score)) +
  geom_density(aes(colour = SEX, linetype = RACE)) +
  scale_fill_manual(values=colorset) +
  scale_colour_manual(values = colorset) +
  labs(x = "Proteomic CRF Score",
       y = "Density",
       title = "Sex and race score distribution",
       subtitle = "All BLSA participants") +
  theme_bw() +
  guides(color=guide_legend(title = "Sex"),
         linetype=guide_legend(title = "Race"))
ggsave("scaled_BLSA_score_sexRace_histos.pdf", width = 4, height = 3)
```

## BMI

```{r}

temp <- all.scores %>% mutate(d = densCols(all.scores$BMI, all.scores$G22DURTN_score, colramp = colorRampPalette(rev(rainbow(10, end = 4/6)))))


ggplot(data=temp, aes(x=BMI, y=G22DURTN_score)) +
  geom_point(size=0.5, aes(col = d)) +
  scale_color_identity() +
  theme_bw() +
  ggpubr::stat_cor(cor.coef.name = "rho", method="spearman", label.x.npc = "right", hjust=1) +
  labs(title = "BLSA LASSO model performance",
       subtitle = "All BLSA participants",
       y = "Proteomic CRF Score",
       x = "Body mass index")
ggsave("scaled_BLSA_score_bmi_corr.pdf", width = 4, height = 3)
```